test_that("function test", {
   curr_working_dir <- getwd()
   test_filename <- make_filename(2013)
   expect_that(test_filename, is_a("character"))
   expect_that(nchar(test_filename), equals(21))
   test_file <- system.file("extdata", test_filename, package="RPackageCoursera")
   setwd(system.file("extdata", package = "RPackageCoursera"))
   fars_data <- fars_read(test_file)
   expect_that(dplyr::is.tbl(fars_data), is_true())
   fars_summary <- fars_summarize_years(c(2013, 2014))
   expect_that(dplyr::is.tbl(fars_summary), is_true())
   expect_that(dim(fars_summary), equals(c(12, 3)))
   setwd(curr_working_dir)
})